Chart.defaults.color = '#475569';
Chart.defaults.font.family = 'Inter, system-ui, -apple-system, sans-serif';
Chart.defaults.font.size = 12;
Chart.defaults.plugins.tooltip.backgroundColor = '#0f172a';
Chart.defaults.plugins.tooltip.borderColor = '#1e293b';
Chart.defaults.plugins.tooltip.borderWidth = 1;
Chart.defaults.plugins.tooltip.titleFont = { weight: '600', size: 13 };
Chart.defaults.plugins.tooltip.bodyFont = { size: 12 };
Chart.defaults.plugins.tooltip.padding = 10;
Chart.defaults.scale.grid.color = '#e2e8f0';
Chart.defaults.scale.ticks.color = '#475569';

function switchTab(id, btn) {
  document.querySelectorAll('.tab').forEach(t => {
    t.classList.remove('active');
    t.setAttribute('aria-selected', 'false');
  });
  document.querySelectorAll('.panel').forEach(p => p.classList.remove('active'));
  document.getElementById('tab-' + id).classList.add('active');
  btn.classList.add('active');
  btn.setAttribute('aria-selected', 'true');
}
window.switchTab = switchTab;

// ─── AUTO-GENERATED FROM: MVLOAD_17_06_2026.xlsx ───────────────────────────
// Report Date : June 17, 2026
// Generated by MVIKAS Dashboard Processor

// NOTE: Monthly targets loaded from Tonnage_of_June_Month sheet
// Achieved = tonnage dispatched so far this month (June 2026)

const clients = [
  { name: 'Carrier Refrigeration',         person: 'Sangeet Dhasmana', target: 315000, achieved: 100425.93, activeDays: 17 },
  { name: 'Bombax',                         person: 'Chirag Kumar',     target: 130812, achieved: 59014.52,  activeDays: 17 },
  { name: 'Carrier CTD',                    person: 'Deepak Sharma',    target: 52221,  achieved: 14385.03,  activeDays: 17 },
  { name: 'Kumar Services',                 person: 'Deepak Sharma',    target: 13995,  achieved: 8390.89,   activeDays: 17 },
  { name: 'Loom Solar Pvt Ltd',             person: 'Deepak Sharma',    target: 29505,  achieved: 7840.00,   activeDays: 17 },
  { name: 'Haier CCR',                      person: 'Shiva',            target: 41726,  achieved: 8238.01,   activeDays: 17 },
  { name: 'Cosmos Pumps Pvt Ltd',           person: 'Shiva',            target: 19027,  achieved: 5144.48,   activeDays: 17 },
  { name: 'Sukuga Technologies Pvt Ltd',    person: 'Shiva',            target: 21318,  achieved: 2930.75,   activeDays: 17 },
  { name: 'Oneiric Appliances Pvt Ltd',     person: 'Deepak Sharma',    target: 6577,   achieved: 2285.00,   activeDays: 17 },
  { name: 'Mitras Technocrafts Pvt Ltd',    person: 'Shiva',            target: 18040,  achieved: 951.05,    activeDays: 17 },
  { name: 'Medical Science',                person: 'Chirag Kumar',     target: 4854,   achieved: 977.00,    activeDays: 17 },
  { name: 'Vaidrishi Laboratories Pvt Ltd', person: 'Chirag Kumar',     target: 3970,   achieved: 579.79,    activeDays: 17 },
  { name: 'Frick India',                    person: 'Shiva',            target: 2840,   achieved: 585.00,    activeDays: 17 },
  { name: 'Paramount Surgimed Ltd',         person: 'Deepak Sharma',    target: 0,      achieved: 400.00,    activeDays: 17 },
  { name: 'Indu Sports',                    person: 'Chirag Kumar',     target: 772,    achieved: 298.00,    activeDays: 17 },
  { name: 'Aurinko Healthcare Pvt Ltd',     person: 'Chirag Kumar',     target: 1059,   achieved: 55.00,     activeDays: 17 },
  { name: 'Grover Innovations LLP',         person: 'Shiva',            target: 17991,  achieved: 0,         activeDays: 17 },
  { name: 'Global Impex',                   person: 'Anjali',           target: 772,    achieved: 0,         activeDays: 17 },
  { name: 'Edusoft Healthcare Ltd',         person: 'Deepak Sharma',    target: 818,    achieved: 0,         activeDays: 17 },
  { name: 'GCPA',                           person: 'Shiva',            target: 0,      achieved: 0,         activeDays: 17 },
  { name: 'Pangea',                         person: 'Deepak Sharma',    target: 0,      achieved: 0,         activeDays: 17 },
  { name: 'RSR',                            person: 'Deepak Sharma',    target: 0,      achieved: 0,         activeDays: 17 },
  { name: 'Epson',                          person: 'Deepak Sharma',    target: 0,      achieved: 0,         activeDays: 17 },
  { name: 'KRF',                            person: 'Not Alloted',      target: 0,      achieved: 0,         activeDays: 17 },
];

clients.forEach(c => {
  c.pct = c.target > 0 ? Math.round(c.achieved / c.target * 100) : (c.achieved > 0 ? 999 : 0);
  c.avgDay = c.activeDays > 0 ? Math.round(c.achieved / c.activeDays) : 0;
  c.remaining = Math.max((c.target || 0) - c.achieved, 0);
  c.daysNeeded = c.avgDay > 0 && c.remaining > 0 ? parseFloat((c.remaining / c.avgDay).toFixed(1)) : (c.remaining === 0 ? 0 : 999);
});

const eddData = [
  { name: 'Bombax',                 count: 96  },
  { name: 'Carrier Refrigeration',  count: 35  },
  { name: 'Haier CCR',              count: 4   },
  { name: 'Sukuga',                 count: 3   },
  { name: 'MITRAS',                 count: 2   },
  { name: 'Oneric Appliances',      count: 2   },
  { name: 'Paramount Surgimed Ltd', count: 1   },
  { name: 'Cosmos Pumps Pvt. Ltd.', count: 1   },
  { name: 'Loom Solar',             count: 1   },
];
const eddTotal = eddData.reduce((a, b) => a + b.count, 0);

const openData = [
  { name: 'Bombax',                   count: 281 },
  { name: 'Carrier Refrigeration',    count: 95  },
  { name: 'Medical Science',          count: 12  },
  { name: 'Sukuga',                   count: 11  },
  { name: 'Oneric Appliances',        count: 5   },
  { name: 'Kumar Services',           count: 5   },
  { name: 'Haier CCR',                count: 4   },
  { name: 'Cosmos Pumps Pvt. Ltd.',   count: 3   },
  { name: 'Carrier - CTD',            count: 3   },
  { name: 'MITRAS',                   count: 2   },
  { name: 'Loom Solar',               count: 2   },
  { name: 'Paramount Surgimed Ltd',   count: 1   },
];
const openTotal = openData.reduce((a, b) => a + b.count, 0);

const dueData = [
  { name: 'Bombax',                 count: 18 },
  { name: 'Carrier Refrigeration',  count: 10 },
  { name: 'Stockarea',              count: 3  },
  { name: 'Kumar Services',         count: 2  },
  { name: 'Sukuga',                 count: 1  },
];
const dueTotal = dueData.reduce((a, b) => a + b.count, 0);

const bookedData = [
  { name: 'Bombax',                 count: 34 },
  { name: 'Carrier Refrigeration',  count: 20 },
  { name: 'Medical Science',        count: 12 },
  { name: 'Kumar Services',         count: 3  },
  { name: 'Loom Solar',             count: 1  },
];
const bookedTotal = bookedData.reduce((a, b) => a + b.count, 0);

const dailyTonnageData = [
  { name: 'Carrier Refrigeration',  kg: 4968.00 },
  { name: 'Bombax',                 kg: 3955.10 },
  { name: 'Loom Solar',             kg: 2200.00 },
  { name: 'Kumar Services',         kg: 579.93  },
  { name: 'Medical Science',        kg: 816.00  },
];
const dailyTotal = dailyTonnageData.reduce((a, b) => a + b.kg, 0);

const monthlyTotal = clients.reduce((a, c) => a + c.achieved, 0);
const daysInMonth = 30; // June has 30 days
const activeDaysElapsed = 17;
const dailyAverage = monthlyTotal / activeDaysElapsed; // avg over active days

// ─── UPDATE HEADER ─────────────────────────────────────────────────────────────
const elDate = document.querySelector('.badge-date');
const elElapsed = document.querySelector('.badge-elapsed');
if (elDate) elDate.textContent = 'As of June 17, 2026';
if (elElapsed) elElapsed.textContent = '17 / 30 days elapsed · June 2026';

// ─── UPDATE KPI CARDS ─────────────────────────────────────────────────────────
document.getElementById('kpi-open').textContent = openTotal;
document.getElementById('kpi-edd').textContent = eddTotal;
document.getElementById('kpi-edd-pct').textContent = Math.round(eddTotal / openTotal * 100) + '% of open';
document.getElementById('kpi-due').textContent = dueTotal;
document.getElementById('kpi-booked').textContent = bookedTotal;
try { document.getElementById('kpi-booked').closest('.metric').querySelector('.metric-sub').textContent = 'June 17, 2026'; } catch(e){}
document.getElementById('kpi-daily-ton').innerHTML = dailyTotal.toLocaleString('en-IN', { maximumFractionDigits: 2 }) + ' <span style="font-size:0.9rem;font-weight:600">kg</span>';
document.getElementById('kpi-month-ton').innerHTML = monthlyTotal.toLocaleString('en-IN', { maximumFractionDigits: 2 }) + ' <span style="font-size:0.9rem;font-weight:600">kg</span>';
try { document.getElementById('kpi-month-ton').closest('.metric').querySelector('.metric-sub').textContent = 'June 2026 cumulative'; } catch(e){}
document.getElementById('kpi-daily-avg').innerHTML =
  dailyAverage.toLocaleString('en-IN', { maximumFractionDigits: 0 }) +
  ' <span style="font-size:0.9rem;font-weight:600">kg/day</span>';

// ─── OPEN SHIPMENTS TABLE (Panel 1) ───────────────────────────────────────────
const openTableBody = document.getElementById('open-table-body');
if (openTableBody) {
  openTableBody.innerHTML = '';
  openData.forEach((d, i) => {
    const eddCount = (eddData.find(e => e.name === d.name) || {}).count || 0;
    const dueCount = (dueData.find(e => e.name === d.name) || {}).count || 0;
    const pctDelayed = Math.round(eddCount / d.count * 100);
    const risk = pctDelayed >= 70 ? ['Critical','delayed'] : pctDelayed >= 40 ? ['High','delayed'] : pctDelayed >= 20 ? ['Medium','open'] : ['Low','due'];
    openTableBody.innerHTML += `<tr>
      <td style="color:#94a3b8;font-size:0.8rem">${i+1}</td>
      <td><strong>${d.name}</strong></td>
      <td>${d.count}</td>
      <td style="color:#dc2626;font-weight:600">${eddCount}</td>
      <td style="color:#d97706;font-weight:600">${dueCount}</td>
      <td style="color:${pctDelayed>=50?'#dc2626':'#d97706'};font-weight:700">${pctDelayed}%</td>
      <td><span class="badge ${risk[1]}">${risk[0]}</span></td>
    </tr>`;
  });
}

// ─── CHART 1: Status Donut ─────────────────────────────────────────────────────
new Chart(document.getElementById('statusDonut'), {
  type: 'doughnut',
  data: {
    labels: ['EDD Crossed (Delayed)', 'Open (in transit)', 'Due Tomorrow', 'Booked Yesterday'],
    datasets: [{
      data: [eddTotal, openTotal - eddTotal, dueTotal, bookedTotal],
      backgroundColor: ['#ef4444', '#3b82f6', '#f59e0b', '#10b981'],
      borderWidth: 2, borderColor: '#ffffff', hoverOffset: 6
    }]
  },
  options: {
    responsive: true, maintainAspectRatio: false, cutout: '68%',
    plugins: {
      legend: { display: false },
      tooltip: { callbacks: { label: ctx => ` ${ctx.label}: ${ctx.parsed}` } }
    }
  }
});

// ─── CHART 2: EDD Crossed by Customer ────────────────────────────────────────
new Chart(document.getElementById('eddBarChart'), {
  type: 'bar',
  data: {
    labels: eddData.map(d => d.name),
    datasets: [{
      label: 'EDD Crossed',
      data: eddData.map(d => d.count),
      backgroundColor: 'rgba(239,68,68,0.12)',
      borderColor: '#ef4444',
      borderWidth: 1.5, borderRadius: 4
    }]
  },
  options: {
    indexAxis: 'y', responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { beginAtZero: true, ticks: { font: { size: 11 } } },
      y: { ticks: { font: { size: 11, weight: '500' } }, grid: { display: false } }
    }
  }
});

// ─── CHART 3: Due Tomorrow (June 3) ───────────────────────────────────────────
new Chart(document.getElementById('dueTmrChart'), {
  type: 'bar',
  data: {
    labels: dueData.map(d => d.name),
    datasets: [{
      label: 'Due Tomorrow',
      data: dueData.map(d => d.count),
      backgroundColor: 'rgba(245,158,11,0.12)',
      borderColor: '#f59e0b',
      borderWidth: 1.5, borderRadius: 4
    }]
  },
  options: {
    responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { ticks: { autoSkip: false, maxRotation: 30, font: { size: 11, weight: '500' } }, grid: { display: false } },
      y: { beginAtZero: true }
    }
  }
});

// ─── CHART 4: Booked Yesterday (June 1) ───────────────────────────────────────
new Chart(document.getElementById('bookedChart'), {
  type: 'bar',
  data: {
    labels: bookedData.map(d => d.name),
    datasets: [{
      label: 'Booked Yesterday',
      data: bookedData.map(d => d.count),
      backgroundColor: 'rgba(16,185,129,0.12)',
      borderColor: '#10b981',
      borderWidth: 1.5, borderRadius: 4
    }]
  },
  options: {
    responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { ticks: { autoSkip: false, maxRotation: 30, font: { size: 11, weight: '500' } }, grid: { display: false } },
      y: { beginAtZero: true }
    }
  }
});

// ─── PANEL 2: Tonnage — showing achieved vs target ────────────────────────────
const barsEl = document.getElementById('tonnage-bars');
if (barsEl) {
  const clientsWithAchieved = clients.filter(c => c.achieved > 0).sort((a, b) => b.achieved - a.achieved);
  clientsWithAchieved.forEach(c => {
    const pct = c.target > 0 ? Math.min(Math.round(c.achieved / c.target * 100), 100) : null;
    const barWidth = pct !== null ? pct + '%' : '100%';
    const barColor = pct !== null ? (pct >= 100 ? '#10b981' : '#004df5') : '#3b82f6';
    const pctLabel = pct !== null ? pct + '%' : '—';
    const pctColor = pct !== null ? (pct >= 100 ? '#10b981' : '#004df5') : '#94a3b8';
    barsEl.innerHTML += `<div class="client-row">
      <div class="client-name" title="${c.name}">${c.name}</div>
      <div class="client-person">${c.person}</div>
      <div class="prog-bar-wrap">
        <div class="prog-bar" style="width:${barWidth};background:linear-gradient(90deg,${barColor},${barColor}99)"></div>
      </div>
      <div class="pct-text" style="color:${pctColor};font-size:0.75rem">${pctLabel}</div>
      <div class="client-tonnage">${(c.achieved/1000).toFixed(2)}T</div>
    </div>`;
  });
}

const chartFont = { size: 11, weight: '500' };
const clientsWithAchieved = clients.filter(c => c.achieved > 0).sort((a, b) => b.achieved - a.achieved);
const top8 = clientsWithAchieved.slice(0, 8);

// ─── CHART 5: Target vs Achieved Tonnage ─────────────────────────────────────
new Chart(document.getElementById('targetChart'), {
  type: 'bar',
  data: {
    labels: top8.map(c => c.name),
    datasets: [
      { label: 'Target (kg)', data: top8.map(c => c.target || 0), backgroundColor: 'rgba(0,77,245,0.10)', borderColor: '#004df5', borderWidth: 1.5, borderRadius: 4 },
      { label: 'Achieved (kg)', data: top8.map(c => c.achieved), backgroundColor: 'rgba(16,185,129,0.20)', borderColor: '#10b981', borderWidth: 1.5, borderRadius: 4 }
    ]
  },
  options: {
    indexAxis: 'y', responsive: true, maintainAspectRatio: false,
    plugins: {
      legend: { position: 'bottom', labels: { boxWidth: 12, padding: 16, font: chartFont } },
      title: { display: true, text: 'Target vs Achieved — June 2026', font: { size: 11 }, color: '#94a3b8' }
    },
    scales: {
      x: { beginAtZero: true, ticks: { callback: v => (v/1000).toFixed(0)+'k', font: chartFont } },
      y: { ticks: { font: chartFont }, grid: { display: false } }
    }
  }
});

// ─── CHART 6: Achieved tonnage bar (since no target) ─────────────────────────
new Chart(document.getElementById('achChart'), {
  type: 'bar',
  data: {
    labels: top8.map(c => c.name),
    datasets: [
      { label: 'Achieved (kg)', data: top8.map(c => c.achieved), backgroundColor: 'rgba(16,185,129,0.15)', borderColor: '#10b981', borderWidth: 1.5, borderRadius: 4 }
    ]
  },
  options: {
    indexAxis: 'y', responsive: true, maintainAspectRatio: false,
    plugins: {
      legend: { position: 'bottom', labels: { boxWidth: 12, padding: 16, font: chartFont } },
      title: { display: true, text: 'June 2026 — Day 17 of month', font: { size: 11 }, color: '#94a3b8' }
    },
    scales: {
      x: { beginAtZero: true, ticks: { callback: v => (v/1000).toFixed(0)+'k', font: chartFont } },
      y: { ticks: { font: chartFont }, grid: { display: false } }
    }
  }
});

// ─── PANEL 3: Daily Average Table ─────────────────────────────────────────────
const tbody = document.getElementById('daily-table-body');
if (tbody) {
  clients.filter(c => c.achieved > 0).forEach(c => {
    const pct      = c.target > 0 ? Math.round(c.achieved / c.target * 100) + '%' : '—';
    const pctColor = c.target > 0 ? (c.achieved >= c.target ? '#10b981' : '#004df5') : '#94a3b8';
    const remaining = c.target > 0 ? Math.max(c.target - c.achieved, 0).toLocaleString('en-IN') : '—';
    const daysToFinish = c.target > 0 && c.avgDay > 0 && c.remaining > 0
      ? parseFloat((c.remaining / c.avgDay).toFixed(1))
      : (c.target > 0 && c.remaining === 0 ? '✓' : '—');
    const targetDisplay = c.target > 0 ? c.target.toLocaleString('en-IN') : '—';
    tbody.innerHTML += `<tr>
      <td style="font-weight:600">${c.name}</td>
      <td style="font-size:0.8rem;color:#64748b">${c.person}</td>
      <td>${targetDisplay}</td>
      <td>${c.achieved.toLocaleString('en-IN')}</td>
      <td style="color:${pctColor};font-weight:700">${pct}</td>
      <td>${c.activeDays}</td>
      <td>${c.avgDay.toLocaleString('en-IN')}</td>
      <td style="color:#f59e0b">${remaining}</td>
      <td style="color:#ef4444">${daysToFinish}</td>
    </tr>`;
  });
}

// ─── CHART 7: Avg kg/day ──────────────────────────────────────────────────────
const topAvg = clients.filter(c => c.avgDay > 0).sort((a, b) => b.avgDay - a.avgDay).slice(0, 10);
new Chart(document.getElementById('avgDayChart'), {
  type: 'bar',
  data: {
    labels: topAvg.map(c => c.name),
    datasets: [{ label: 'Avg kg/day', data: topAvg.map(c => c.avgDay), backgroundColor: 'rgba(99,102,241,0.12)', borderColor: '#6366f1', borderWidth: 1.5, borderRadius: 4 }]
  },
  options: {
    indexAxis: 'y', responsive: true, maintainAspectRatio: false,
    plugins: { legend: { display: false } },
    scales: {
      x: { beginAtZero: true, ticks: { callback: v => v.toLocaleString('en-IN'), font: chartFont } },
      y: { ticks: { font: chartFont }, grid: { display: false } }
    }
  }
});

// ─── CHART 8: Days to Complete ────────────────────────────────────────────────
const daysChartEl = document.getElementById('daysChart');
if (daysChartEl) {
  const daysData = clients.filter(c => c.target > 0 && c.avgDay > 0 && c.remaining > 0)
    .sort((a, b) => b.daysNeeded - a.daysNeeded).slice(0, 10);
  new Chart(daysChartEl, {
    type: 'bar',
    data: {
      labels: daysData.map(c => c.name),
      datasets: [{
        label: 'Days to finish remaining target',
        data: daysData.map(c => c.daysNeeded),
        backgroundColor: daysData.map(c => c.daysNeeded > 18 ? 'rgba(239,68,68,0.18)' : 'rgba(245,158,11,0.18)'),
        borderColor: daysData.map(c => c.daysNeeded > 18 ? '#ef4444' : '#f59e0b'),
        borderWidth: 1.5, borderRadius: 4
      }]
    },
    options: {
      indexAxis: 'y', responsive: true, maintainAspectRatio: false,
      plugins: {
        legend: { display: false },
        title: { display: true, text: 'Estimated days to finish at current avg rate', font: { size: 11 }, color: '#94a3b8' }
      },
      scales: {
        x: { beginAtZero: true, ticks: { font: chartFont } },
        y: { ticks: { font: chartFont }, grid: { display: false } }
      }
    }
  });
}

// ─── PANEL 4: KAM-wise breakdown ──────────────────────────────────────────────
const kamMap = {};
clients.filter(c => c.achieved > 0).forEach(c => {
  if (!kamMap[c.person]) kamMap[c.person] = { person: c.person, totalTarget: 0, totalAchieved: 0, clients: [] };
  kamMap[c.person].totalTarget += c.target;
  kamMap[c.person].totalAchieved += c.achieved;
  kamMap[c.person].clients.push(c);
});
const kamList = Object.values(kamMap).sort((a, b) => b.totalAchieved - a.totalAchieved);

const kamTbody = document.getElementById('kam-table-body');
if (kamTbody) {
  kamList.forEach(k => {
    kamTbody.innerHTML += `<tr>
      <td style="font-weight:700">${k.person}</td>
      <td>${k.clients.length}</td>
      <td>${k.totalTarget > 0 ? k.totalTarget.toLocaleString('en-IN') : '—'}</td>
      <td>${k.totalAchieved.toLocaleString('en-IN')}</td>
      <td style="color:#004df5;font-weight:700">${k.totalTarget > 0 ? Math.round(k.totalAchieved / k.totalTarget * 100) + '%' : '—'}</td>
      <td>
        <div style="background:#e2e8f0;border-radius:99px;height:8px;overflow:hidden;width:120px">
          <div style="height:100%;border-radius:99px;width:${k.totalTarget > 0 ? Math.min(Math.round(k.totalAchieved/k.totalTarget*100),100) : 100}%;background:linear-gradient(90deg,#004df5,#3b82f6)"></div>
        </div>
      </td>
    </tr>`;
  });
}

new Chart(document.getElementById('kamDonut'), {
  type: 'doughnut',
  data: {
    labels: kamList.map(k => k.person),
    datasets: [{
      data: kamList.map(k => k.totalAchieved),
      backgroundColor: ['#004df5', '#10b981', '#f59e0b', '#ef4444', '#6366f1', '#ec4899'],
      borderWidth: 2, borderColor: '#fff', hoverOffset: 6
    }]
  },
  options: {
    responsive: true, maintainAspectRatio: false, cutout: '62%',
    plugins: {
      legend: { position: 'bottom', labels: { boxWidth: 12, padding: 12, font: { size: 11 } } },
      tooltip: { callbacks: { label: ctx => ` ${ctx.label}: ${(ctx.parsed / 1000).toFixed(2)}T` } }
    }
  }
});
